In [1]:
import numpy as np

In [132]:
def area(P):
    area = 0
    matriz = np.array(P)
    matriz = np.concatenate((matriz, matriz[:1]), axis=0)
    for i in range(matriz.shape[0] - 1):
        mini_matriz = np.vstack((matriz[i], matriz[i+1]))
        area += np.linalg.det(mini_matriz)
    area = (np.abs(area)/2)
    print('%.1f'% area)
    
area([[1,2],[3,4],[5,7],[2,10]])

14.5


In [129]:
def mul(A,B):
    matrizA, matrizB = np.matrix(A, dtype=float), np.matrix(B, dtype=float)
    if matrizA.shape[1] != matrizB.shape[0]:
        print("Não existe multiplicação entre essas matrizes")
    else:
        print(np.dot(matrizA,matrizB))
                

mul([[1,-1,1],[-3,2,-1],[-2,1,0]],[[1,2,3],[20,40,60],[1,2,3]])

[[-18. -36. -54.]
 [ 36.  72. 108.]
 [ 18.  36.  54.]]


In [124]:
def interno(u, v):
    vetor_u, vetor_v = np.array(u), np.array(v)
    print(np.dot(vetor_u, vetor_v))
    
interno([1,2,3],[2,3,4])

20


In [45]:
def normainf(u):
    vetor = np.array(u)
    print(vetor.max())
    
normainf([1,2,3])

3


In [71]:
def normau(u):
    vetor = np.array(u)
    print(np.sum(np.abs(vetor)))
    
normau([1,2,3])

6


In [74]:
def tr(A):
    matriz = np.matrix(A)
    soma = 0
    for i in range(len(matriz.shape)):
        for j in range(len(matriz.shape)):
            if i == j:
                soma += matriz[i,j]
    print(soma)
    
tr([[1,-1,1],[-3,2,-1],[-2,1,0]])

3


In [136]:
def normap(u,p):
    vetor = np.array(u)
    vetor = np.power(np.abs(vetor), p)
    soma = np.sum(vetor)
    modulo = np.power(soma, (1/p))
    print(modulo)
    
normap([1 , 0 , -5 , 1.7 , 21.6],3)

21.693128562594516
