In [2]:
import numpy as np

In [4]:
# algoritmo de permutação de linhas
def pij(A,i,j):
    B=np.matrix(A[i])
    A[i],A[j]=A[j],B

def eija(A,i,j,a):
    A[i]+=a*A[j]

def eil(A,i,l):
    A[i]*=l

# executa o algoritmo lu, anotando a permutação das linhas na lista Q
# executa o algoritmo lu, anotando a permutação das linas na lista Q
def plu(M,Q,n):
  for i in range(0,n):
    # anotando e efetuando as permutações necessárias
    if(M[i,i]==0):
      for j in range(i+1,n):
        if (M[j,i]!=0):
          pij(M,j,i)
          t=Q[i]
          Q[i]=Q[j]
          Q[j]=t
          break
    # executando o algoritmo LU
    for j in range(i+1,n):
      M[j,i] /= M[i,i]
      for k in range(i+1,n):
        M[j,k] -= M[j,i]*M[i,k]
# fim do algoritmo plu

def lu(M):
  m,n=np.shape(M)
  if(m!=n):
    print('Erro! Matriz não é quadrada')
    return
  U=np.matrix(M)
  Q=np.zeros(n,dtype=int)
  for i in range(0,n):
    Q[i]=i;
  plu(U,Q,n)

  # separando os fatores L e U
  L=np.identity(n) 
  for i in range(1,n):
    for j in range(0,i):
      L[i,j]=U[i,j]
      U[i,j]=0

  # montando a matriz P a partir da lista Q
  P=np.zeros(np.shape(M),dtype=int)
  for i in range(0,n):
    P[Q[i],i]=1

  # retornando as matrizes obtidas
  return P,L,U
# finalizado

# testando
A=np.matrix([[0.,0.,6.,0.,-5.],
             [2.,2.,-1.,-2.,1.],
             [1.,1.,2.,0.,6.],
             [0.,4.,-2.,3.,-3.],
             [2.,0.,1.,-1.,5.]])
P,L,U=lu(A)

print('P=',P)
print('L=',L)
print('U=',U)
print('PLU=',P@L@U)

P= [[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]]
L= [[ 1.     0.     0.     0.     0.   ]
 [ 0.     1.     0.     0.     0.   ]
 [ 0.5    0.     1.     0.     0.   ]
 [ 0.     0.     2.4    1.     0.   ]
 [ 1.    -0.5    0.4   -0.875  1.   ]]
U= [[  2.      2.     -1.     -2.      1.   ]
 [  0.      4.     -2.      3.     -3.   ]
 [  0.      0.      2.5     1.      5.5  ]
 [  0.      0.      0.     -2.4   -18.2  ]
 [  0.      0.      0.      0.    -15.625]]
PLU= [[ 0.  0.  6.  0. -5.]
 [ 2.  2. -1. -2.  1.]
 [ 1.  1.  2.  0.  6.]
 [ 0.  4. -2.  3. -3.]
 [ 2.  0.  1. -1.  5.]]


In [44]:
def inv(A):
    m,n=np.shape(A)
    P,L,U=lu(A)
    identidade = np.identity(n)
    inv_A = np.zeros((m,m))
    I = P@identidade
    for i in range(m):
        y = np.linalg.solve(L,I[i])
        x = np.linalg.solve(U,y)
        inv_A[:, i] = x
    
    return inv_A

In [46]:
A=np.matrix([[0.,0.,6.,0.,-5.],
             [2.,2.,-1.,-2.,1.],
             [1.,1.,2.,0.,6.],
             [0.,4.,-2.,3.,-3.],
             [2.,0.,1.,-1.,5.]])
print(inv(A))
print(A.getI())

[[ 0.084      -0.14266667 -0.57333333  0.21466667  0.92933333]
 [ 0.012       0.26533333  0.34666667  0.03066667 -0.43866667]
 [ 0.12       -0.01333333  0.13333333 -0.02666667 -0.05333333]
 [ 0.008      -0.37866667 -0.21333333  0.24266667  0.48533333]
 [-0.056      -0.016       0.16       -0.032      -0.064     ]]
[[ 0.084      -0.14266667 -0.57333333  0.21466667  0.92933333]
 [ 0.012       0.26533333  0.34666667  0.03066667 -0.43866667]
 [ 0.12       -0.01333333  0.13333333 -0.02666667 -0.05333333]
 [ 0.008      -0.37866667 -0.21333333  0.24266667  0.48533333]
 [-0.056      -0.016       0.16       -0.032      -0.064     ]]
